import React from 'react'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { ForbiddenPage } from 'components'
import { Locale } from 'types'
import Head from 'next/head'

const Forbidden = () => {
  return (
    <>
      <Head>
        <title>Epic-movie-quotes</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <ForbiddenPage />
    </>
  )
}
export const getStaticProps = async ({ locale }: Locale) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['403', 'common'])),
    },
  }
}

export default Forbidden
