import Head from 'next/head'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { LandingPage } from 'components'
export const getStaticProps = async ({ locale }: { locale: string }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['home'])),
    },
  }
}

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <LandingPage />
    </>
  )
}
export default Home
