import React from 'react'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { Locale } from 'types'
import { ProfilePageMain } from 'components'
import Head from 'next/head'

const ProfilePage = () => {
  return (
    <>
      <Head>
        <title>Epic-movie-quotes</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <ProfilePageMain />
    </>
  )
}
export const getStaticProps = async ({ locale }: Locale) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, [
        'profile',
        'common',
        'errors',
      ])),
    },
  }
}

export default ProfilePage
